# Generated by Django 3.2.6 on 2024-10-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoPendiente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valorPendiente', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('fechaLimite', models.CharField(max_length=100)),
                ('descuento', models.FloatField()),
                ('interes', models.FloatField()),
                ('estaPagado', models.BooleanField(default=False)),
            ],
        ),
    ]
