# Generated by Django 3.2.6 on 2024-10-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('saldos_pendientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronogramaPersonalizado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('saldo_pendiente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saldos_pendientes.saldopendiente')),
            ],
        ),
    ]
