# Generated by Django 3.2.6 on 2024-10-18 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cronogramas_personalizados', '0001_initial'),
        ('saldos_pendientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=50)),
                ('curso', models.CharField(max_length=100)),
                ('cronograma_personalizado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cronogramas_personalizados.cronogramapersonalizado')),
                ('saldo_pendiente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='saldos_pendientes.saldopendiente')),
            ],
        ),
    ]
